config/routes.rb
CoderetreatLive::Application.routes.draw do
  resources :coderetreats, only: [] do
    get :running_today, :on => :collection
    get :edit_status, :on => :member
    put :update_status, :on => :member
  end
end

app/models/coderetreat.rb
class Coderetreat < ActiveRecord::Base
  attr_accessible :location, :status
  def self.running_today
   all 
  end
  def update_status(new_status)
    self.update_attributes(status: new_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/coderetreats_controller.rb
require 'coderetreats'
require 'coderetreats/status'

class CoderetreatsController < ApplicationController
  def running_today
    @coderetreats = CoderetreatLive::Coderetreats.running_today
  end

  def edit_status
    @coderetreat = Coderetreat.find(coderetreat_id)
  end
  
  def update_status
    CoderetreatLive::Coderetreats::Status.update_to(coderetreat_id, params[:new_status])
    redirect_to edit_status_coderetreat_url(coderetreat_id)
  end

  private 
  def coderetreat_id
    coderetreat_id = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coderetreats_helper.rb
module CoderetreatsHelper
end

app/views/coderetreats/edit_status.html.haml
%h1 Edit the status for #{@coderetreat.location}

=form_for @coderetreat, url: update_status_coderetreat_path(@coderetreat, new_status: 'in_session'), method: :put do |f|
  =f.submit 'Start session'

app/views/coderetreats/running_today.html.haml
There are no coderetreats running today

%section.coderetreats.not_started
  %header
    %h2 Not started
  %ul
    - @coderetreats.not_started do |coderetreat|
      %li.coderetreat=coderetreat.location
%section.coderetreats.in_session
  %header
    %h2 In Session
  %ul
    - @coderetreats.in_session do |coderetreat|
      %li.coderetreat=coderetreat.location

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderetreatLive</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>